### ISSUE TITLE
[WDSR] order of residual scaling and element-wise sum

### ISSUE THREAD

**Issue by htleeab** [krasserm/super-resolution#25]
From the paper of EDSR, 
> We resolve this issue by adopting the residual scaling [24] with factor 0.1. In each residual block, constant scaling layers are placed after the last convolution layers.

In this re-implemented code, it seem that scaling is placed after element-wise sum.

https://github.com/krasserm/super-resolution/blob/4beed440353c5d93390fbd661c54cfcbb2e318b9/model/wdsr.py#L42-L61

Original WDSR PyTorch implementation:
https://github.com/JiahuiYu/wdsr_ntire2018/blob/cd2053e20579a020f609459d795656590dc98307/wdsr_b.py#L25-L28

I'm not familiar with PyTorch. I'm wondering should the residual scaling put before element-wise sum?

**Comment by krasserm** [comment]
You're completely right, that's indeed a bug, thanks for catching it @htleeab. The bug is in both, the edsr and wdsr model implementations. Pre-trained models aren't affected though as these are only baseline models and the scaling is set to 1.0 for them. Feel free to create a pull request (to master and maybe also to wip-tf2) if you want, otherwise, I'll fix that later. Thanks again!
